// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUdpRlurG23oPMRdfwaUoxIRXu15oaMc4',
    appId: '1:39552132564:android:591d6dee4237b5ea412241',
    messagingSenderId: '39552132564',
    projectId: 'cinec-movie-booking-9f73c',
    databaseURL: 'https://cinec-movie-booking-9f73c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cinec-movie-booking-9f73c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDiZhl5H4lsZ-UIu3mXCqxP8-PDj3HPis',
    appId: '1:39552132564:ios:ff7f2cb3af6c5893412241',
    messagingSenderId: '39552132564',
    projectId: 'cinec-movie-booking-9f73c',
    databaseURL: 'https://cinec-movie-booking-9f73c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cinec-movie-booking-9f73c.firebasestorage.app',
    iosBundleId: 'com.example.cinecMovieBooking',
  );
}
