import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:get_storage/get_storage.dart';

import 'app.dart';
import 'firebase_options.dart'; // Make sure this is generated by `flutterfire configure`

/// ---------- Entry Point of Flutter App ----------
Future<void> main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize GetStorage (if using local storage)
  await GetStorage.init();

  // Run the App
  runApp(const App());
}
